### ISSUE TITLE
Multiple jobs launched on new GitOpsConfig

### ISSUE THREAD

**Issue by jkupferer** [KohlsTechnology/eunomia#100] opened 2019-09-12 15:03 UTC
Eunomia launches multiple jobs for the same GitOpsConfig, it appears it is reacting to the initial job creation and then to its own updates to the GitOpsConfig, such as adding `spec.parameterSource`.

**Comment by seanmalloy** [comment] 2019-10-21 04:30
@jkupferer does this happen every time or only under certain conditions? Is there anything specific that you are doing to reproduce this error?

**Comment by akavel** [comment] 2019-10-28 15:37
Hi @jkupferer! I'm trying to learn this codebase and take a shot at hopefully fixing this issue. Is there any chance you could try and come up with some explicit steps how to reproduce? that could *reeeeally* help me jump to actually trying to track and fix the issue, whereas now I'm still slowly gnawing at the very early "trying to reproduce" phase... :)

**Comment by seanmalloy** [comment] 2019-10-28 18:43
@jkupferer as mentioned by @akavel we are not able to reproduce this issues. Can you please provide some details on how to reproduce this?

**Comment by akavel** [comment] 2019-11-08 11:31
@seanmalloy would you be ok if we close this with a new 'cannot reproduce' label?

**Comment by seanmalloy** [comment] 2019-11-08 15:16
@akavel sure. I'll close out this issue. It can be re-opened in the future if someone can provided details steps on how to reproduce this.

**Closed by seanmalloy** 2019-11-08 15:16 UTC
Labels: bug, cannot reproduce
