### ISSUE TITLE
Webhook does not create reconciliation job in "external namespaces"

### ISSUE THREAD

**Issue by vinny-sabatini** [KohlsTechnology/eunomia#270] opened 2020-01-28 21:50 UTC
**What version of eunomia are you using?**

eunomia version: v0.1.1

**Does this issue reproduce with the latest release?**

Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-03-19T15:41:07Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

I setup Eunomia in `namespace-a` and created the webhook route.
I created `namespace-b` and added a GitOpsConfig with a `Webhook` trigger to it.
I setup the webhook in my GitHub repository, and then pushed a commit to trigger the webhook.

**What did you expect to see?**

I expected to see a reconciliation job start in `namespace-b`

**What did you see instead?**

The Eunomia Operator received the webhook, and it did not trigger a reconciliation job in `namespace-b`. The operator printed these logs:
```
{"level":"info","ts":1580247241.0953147,"logger":"handler","msg":"received webhook call"}
{"level":"info","ts":1580247241.0965447,"logger":"handler","msg":"webhook handling concluded correctly"}
{"level":"info","ts":1580247241.0966249,"logger":"gitopsconfig-controller","msg":"Reconciling GitOpsConfig","Request.Namespace":"","Request.Name":""}
```

**Comment by akavel** [comment] 2020-01-29 14:10
This looks to me like an issue in webook handler code. Reconciler gets a Request with empty name and namespace, so I assume handler inserted some invalid data into PushEvents. My initial guess would be that maybe reconciler.GetAll() fails to list all GitOpsConfig objects in all namespaces? Though I may well be wrong, that's just a hypothesis; we need to add a bit more logs in this area.

**Comment by sbar95** [comment] 2020-02-24 11:28
@vinny-sabatini What setup did you exactly have? I'm not able to reproduce it (I'm using Eunomia from master branch). I set up a local Minikube cluster with Eunomia deployed to `eunomia-operator` namespace, and webhook port exposed to external network with the use of Ngrok.

I configured the webhook in my remote fork, and created `eunomia-hello-world-yaml` namespace where I've deployed a GitOpsConfig:
```
apiVersion: eunomia.kohls.io/v1alpha1
kind: GitOpsConfig
metadata:
  name: hello-world-yaml
spec:
  templateSource:
    uri: https://github.com/sbar95/eunomia
    ref: master
    contextDir: examples/hello-world-yaml/template1
  parameterSource:
    ref: master
    contextDir: examples/hello-world-yaml/parameters
  triggers:
  - type: Webhook
  serviceAccountRef: eunomia-runner-yaml
  templateProcessorImage: quay.io/kohlstechnology/eunomia-base:dev
  resourceHandlingMode: Apply
  resourceDeletionMode: Delete
```

After this the `hello-world` application's been successfully deployed:
<details><summary><code>kubectl get all -n eunomia-hello-world-yaml-demo</code></summary><br><pre>
$ kubectl get all -n eunomia-hello-world-yaml-demo
NAME                                             READY   STATUS      RESTARTS   AGE
pod/gitopsconfig-hello-world-yaml-xcmvmg-z6mpz   0/1     Completed   0          2m5s
pod/hello-world-7b7f58765c-vb9mn                 1/1     Running     0          115s

NAME                  TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
service/hello-world   NodePort   10.96.227.18   <none>        8080:32043/TCP   115s

NAME                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/hello-world   1/1     1            1           115s

NAME                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/hello-world-7b7f58765c   1         1         1       115s

NAME                                             COMPLETIONS   DURATION   AGE
job.batch/gitopsconfig-hello-world-yaml-xcmvmg   1/1           15s        2m5s
</pre></details>

Then, I created a push to my fork [with 3 replicas instead of 1](https://github.com/sbar95/eunomia/commit/bd4be9a160bdeb3e9c3c9c6714aa376d9f702135). The result was a reconciliation job in the `eunomia-hello-world-yaml` namespace:
<details><summary><code>kubectl get all -n eunomia-hello-world-yaml-demo</code></summary><br><pre>
$ kubectl get all -n eunomia-hello-world-yaml-demo
NAME                                             READY   STATUS      RESTARTS   AGE
pod/gitopsconfig-hello-world-yaml-4hn0nn-djfcn   0/1     Completed   0          15s
pod/gitopsconfig-hello-world-yaml-xcmvmg-z6mpz   0/1     Completed   0          2m51s
pod/hello-world-7b7f58765c-bxw5v                 1/1     Running     0          6s
pod/hello-world-7b7f58765c-vb9mn                 1/1     Running     0          2m41s
pod/hello-world-7b7f58765c-w6bsh                 1/1     Running     0          6s

NAME                  TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
service/hello-world   NodePort   10.96.227.18   <none>        8080:32043/TCP   2m41s

NAME                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/hello-world   3/3     3            3           2m41s

NAME                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/hello-world-7b7f58765c   3         3         3       2m41s

NAME                                             COMPLETIONS   DURATION   AGE
job.batch/gitopsconfig-hello-world-yaml-4hn0nn   1/1           14s        15s
job.batch/gitopsconfig-hello-world-yaml-xcmvmg   1/1           15s        2m51s
</pre></details>

<details><summary><code>port-forwarder</code></summary><br><pre>
ngrok by @inconshreveable                                              (Ctrl+C to quit)
                                                                                       
Session Status                online                                                   
Session Expires               7 hours, 31 minutes                                      
Version                       2.3.35                                                   
Region                        United States (us)                                       
Web Interface                 http://127.0.0.1:4040                                    
Forwarding                    http://99414c02.ngrok.io -> http://192.168.64.102:31555  
Forwarding                    https://99414c02.ngrok.io -> http://192.168.64.102:31555 
                                                                                       
Connections                   ttl     opn     rt1     rt5     p50     p90              
                              2       0       0.00    0.00    0.18    0.21             
                                                                                       
HTTP Requests                                                                          
-------------                                                                          
                                                                                       
POST /webhook/                 200 OK                                                  
POST /webhook/                 200 OK                                                  
</pre></details>

<details><summary><code>kubectl logs -f pod/eunomia-operator-86b9c855ff-29c9k -n eunomia-operator</code></summary><br><pre>
$ kubectl logs -f pod/eunomia-operator-86b9c855ff-29c9k -n eunomia-operator
{"level":"info","ts":1582539430.9584155,"logger":"cmd","msg":"Eunomia version: v0.1.4-dev (build date: 20200224-10:05:37, branch: master, git SHA1: 0050d0543db6eabccff89f543e769e9560bf3d74)"}
{"level":"info","ts":1582539430.958621,"logger":"cmd","msg":"Go Version: go1.13.3"}
{"level":"info","ts":1582539430.9587626,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1582539430.9588273,"logger":"cmd","msg":"Version of operator-sdk: v0.8.1"}
{"level":"info","ts":1582539430.9591315,"logger":"cmd","msg":"JOB_TEMPLATE not set. Using default job template."}
{"level":"info","ts":1582539430.959246,"logger":"cmd","msg":"CRONJOB_TEMPLATE not set. Using default job template."}
{"level":"info","ts":1582539430.962132,"logger":"cmd","msg":"Templates initialized correctly"}
{"level":"info","ts":1582539430.9625618,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1582539431.0702035,"logger":"leader","msg":"No pre-existing lock was found."}
{"level":"info","ts":1582539431.0756,"logger":"leader","msg":"Became the leader."}
{"level":"info","ts":1582539431.1674397,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1582539431.1683607,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"gitopsconfig-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1582539431.168666,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"gitopsconfig-controller","source":"channel source: 0xc0006f60f0"}
{"level":"info","ts":1582539431.1766548,"logger":"cmd","msg":"Starting the Web Server"}
{"level":"info","ts":1582539431.176825,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1582539431.3561883,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"gitopsconfig-controller"}
{"level":"info","ts":1582539431.456647,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"gitopsconfig-controller","worker count":1}
{"level":"info","ts":1582541635.9396539,"logger":"handler","msg":"received webhook call"}
{"level":"info","ts":1582541635.940279,"logger":"handler","msg":"unknown event type","type":"ping"}
{"level":"info","ts":1582541945.464478,"logger":"gitopsconfig-controller","msg":"Reconciling GitOpsConfig","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml"}
{"level":"info","ts":1582541945.464526,"logger":"gitopsconfig-controller","msg":"found instance","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1582541945.464532,"logger":"gitopsconfig-controller","msg":"Instance needs to be initialized","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1582541945.468707,"logger":"gitopsconfig-controller","msg":"Reconciling GitOpsConfig","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml"}
{"level":"info","ts":1582541945.4688475,"logger":"gitopsconfig-controller","msg":"found instance","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1582541945.4689605,"logger":"gitopsconfig-controller","msg":"Instance is initialized","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1582541945.4690835,"logger":"gitopsconfig-controller","msg":"Instance has a change or Webhook trigger, creating job","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1582541945.5733507,"logger":"gitopsconfig-controller","msg":"Creating a new Job","job.Namespace":"eunomia-hello-world-yaml-demo","job.Name":"gitopsconfig-hello-world-yaml-xcmvmg"}
{"level":"info","ts":1582541945.5924945,"logger":"gitopsconfig-controller","msg":"unstarted Job found; cannot properly set GitOpsConfig.Status based on it, ignoring","job":"gitopsconfig-hello-world-yaml-xcmvmg"}
{"level":"info","ts":1582542101.26684,"logger":"handler","msg":"received webhook call"}
{"level":"info","ts":1582542101.2714946,"logger":"gitopsconfig-controller","msg":"Reconciling GitOpsConfig","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml"}
{"level":"info","ts":1582542101.274667,"logger":"gitopsconfig-controller","msg":"found instance","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1582542101.2748675,"logger":"gitopsconfig-controller","msg":"Instance is initialized","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1582542101.2748826,"logger":"gitopsconfig-controller","msg":"Instance has a change or Webhook trigger, creating job","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1582542101.2713609,"logger":"handler","msg":"webhook handling concluded correctly"}
{"level":"info","ts":1582542101.2789817,"logger":"gitopsconfig-controller","msg":"Creating a new Job","job.Namespace":"eunomia-hello-world-yaml-demo","job.Name":"gitopsconfig-hello-world-yaml-4hn0nn"}
{"level":"info","ts":1582542101.3042424,"logger":"gitopsconfig-controller","msg":"unstarted Job found; cannot properly set GitOpsConfig.Status based on it, ignoring","job":"gitopsconfig-hello-world-yaml-4hn0nn"}
</pre></details>

**Comment by seanmalloy** [comment] 2020-02-26 05:55
@sbar95 let me know if you still can't reproduce this and I'll close this issue and add the "cannot reproduce" label.

**Comment by sbar95** [comment] 2020-02-26 10:20
@seanmalloy I was trying to reproduce it in serveral environments (Minikube, Minishift, another OpenShift cluster) but in the end everything was always working fine. Even using Eunomia v0.1.1 I wasn't able to reproduce it, unfortunately.

**Comment by vinny-sabatini** [comment] 2020-04-09 20:07
I have run into this issue again while running Eunomia in GKE.

Eunomia version
> eunomia_build_info{branch="HEAD",builddate="20200326-23:01:28",gitsha1="988739ae96d923d1d9913ebeff54dabdae942058",goversion="go1.13.9",operatorsdk="v0.8.1",version="v0.1.6"} 1

Kubernetes version 
> Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.24", GitCommit:"39e41a8d6b7221b901a95d3af358dea6994b4a40", GitTreeState:"clean", BuildDate:"2020-02-29T01:24:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

Some notes for our current deployment that produced the issue:
- The Eunomia operator is running in a namespace named `eunomia-operator`
- We are following the "seed" pattern where one namespace has a "seed" `GitOpsConfig`, which creates the other namespaces and `GitOpsConfig` resources in those namespaces
- All of the `GitOpsConfig` resources have the `Webhook` and the `Change` triggers configured
- The Webhook is configured in a GitHub Enterprise instance, and in GitHub the webhook is showing return code 200, however the log message shows no job is being triggered. I verified in the namespaces no jobs were run and that it was not just a missed log.
```
{"level":"info","ts":1586459363.26891,"logger":"handler","msg":"received webhook call"}
{"level":"info","ts":1586459363.2716246,"logger":"handler","msg":"webhook handling concluded correctly"}
{"level":"info","ts":1586459363.2729392,"logger":"gitopsconfig-controller","msg":"Reconciling GitOpsConfig","Request.Namespace":"","Request.Name":""}
```
- Jobs were created upon restarting the Eunomia operator pod, so it only appears to be the webhook running this issue.

**Closed** 2020-06-04 18:21 UTC
Labels: bug
