### ISSUE TITLE
kubectl delete GitOpsConfig/hello-world-yaml hangs infinitely

### ISSUE THREAD

**Issue by mkyc** [KohlsTechnology/eunomia#115] opened 2019-10-29 18:12 UTC
## What happens?

`kubectl delete -n eunomia-hello-world-yaml-demo   GitOpsConfig/hello-world-yaml` does not work and hangs infinitely

## What were you expecting to happen?

Delete operation should finish and there should be no CR after get operation. 

## Steps to reproduce: 

Follow examples/hello-world-yaml on minikube

## Any errors, stacktrace, logs? 

```
> k get GitOpsConfig --all-namespaces
NAMESPACE                       NAME               AGE
eunomia-hello-world-yaml-demo   hello-world-yaml   22m
> k delete -n eunomia-hello-world-yaml-demo   GitOpsConfig/hello-world-yaml
gitopsconfig.eunomia.kohls.io "hello-world-yaml" deleted
^C
> k get GitOpsConfig --all-namespaces                                      
NAMESPACE                       NAME               AGE
eunomia-hello-world-yaml-demo   hello-world-yaml   30m
```

## Environment:

* Runtime version(Java, Go, Python, etc): minikube

## Additional comments:

v0.0.1

**Comment by seanmalloy** [comment] 2019-10-30 04:40
I believe this is a duplicate of #74 and #52 which are both assigned to @akavel 

@mkyc can you provide the logs from the operator pod? And also provide the output from the command `kubectl delete -v=9 -n eunomia-hello-world-yaml-demo   GitOpsConfig/hello-world-yaml`?

**Comment by akavel** [comment] 2019-10-30 13:18
Yes, I'm basically working on exactly this now (more precisely, with the `...-helm` example, but I assume the underlying reason/mechanism is exactly the same). It reproduces for me repetitively, so I don't think you need to provide the logs, thanks.

**Comment by mkyc** [comment] 2019-10-30 13:19
```
> kubectl delete -v=9 -n eunomia-hello-world-yaml-demo GitOpsConfig/hello-world-yaml
I1030 14:16:27.729000   56329 loader.go:375] Config loaded from file:  /Users/mateusz/.kube/config
I1030 14:16:27.736899   56329 request.go:968] Request Body: {"propagationPolicy":"Background"}
I1030 14:16:27.737260   56329 round_trippers.go:423] curl -k -v -XDELETE  -H "Accept: application/json" -H "Content-Type: application/json" -H "User-Agent: kubectl/v1.16.2 (darwin/amd64) kubernetes/c97fe50" 'https://192.168.64.9:8443/apis/eunomia.kohls.io/v1alpha1/namespaces/eunomia-hello-world-yaml-demo/gitopsconfigs/hello-world-yaml'
I1030 14:16:27.751915   56329 round_trippers.go:443] DELETE https://192.168.64.9:8443/apis/eunomia.kohls.io/v1alpha1/namespaces/eunomia-hello-world-yaml-demo/gitopsconfigs/hello-world-yaml 200 OK in 14 milliseconds
I1030 14:16:27.751933   56329 round_trippers.go:449] Response Headers:
I1030 14:16:27.751938   56329 round_trippers.go:452]     Content-Length: 1802
I1030 14:16:27.751941   56329 round_trippers.go:452]     Date: Wed, 30 Oct 2019 13:16:27 GMT
I1030 14:16:27.751943   56329 round_trippers.go:452]     Cache-Control: no-cache, private
I1030 14:16:27.751946   56329 round_trippers.go:452]     Content-Type: application/json
I1030 14:16:27.751970   56329 request.go:968] Response Body: {"apiVersion":"eunomia.kohls.io/v1alpha1","kind":"GitOpsConfig","metadata":{"annotations":{"gitopsconfig.eunomia.kohls.io/initialized":"true","kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"eunomia.kohls.io/v1alpha1\",\"kind\":\"GitOpsConfig\",\"metadata\":{\"annotations\":{},\"name\":\"hello-world-yaml\",\"namespace\":\"eunomia-hello-world-yaml-demo\"},\"spec\":{\"parameterSource\":{\"contextDir\":\"examples/hello-world-yaml/parameters\",\"ref\":\"master\"},\"resourceDeletionMode\":\"Delete\",\"resourceHandlingMode\":\"CreateOrMerge\",\"serviceAccountRef\":\"eunomia-runner-yaml\",\"templateProcessorImage\":\"quay.io/kohlstechnology/eunomia-base:latest\",\"templateSource\":{\"contextDir\":\"examples/hello-world-yaml/template3\",\"ref\":\"master\",\"uri\":\"https://github.com/KohlsTechnology/eunomia\"},\"triggers\":[{\"type\":\"Change\"}]}}\n"},"creationTimestamp":"2019-10-30T13:14:08Z","deletionGracePeriodSeconds":0,"deletionTimestamp":"2019-10-30T13:16:27Z","finalizers":["eunomia-finalizer"],"generation":5,"name":"hello-world-yaml","namespace":"eunomia-hello-world-yaml-demo","resourceVersion":"5874","selfLink":"/apis/eunomia.kohls.io/v1alpha1/namespaces/eunomia-hello-world-yaml-demo/gitopsconfigs/hello-world-yaml","uid":"8264248b-d66a-48a5-9f63-eaa00882c97c"},"spec":{"parameterSource":{"contextDir":"examples/hello-world-yaml/parameters","ref":"master","uri":"https://github.com/KohlsTechnology/eunomia"},"resourceDeletionMode":"Delete","resourceHandlingMode":"CreateOrMerge","serviceAccountRef":"eunomia-runner-yaml","templateProcessorImage":"quay.io/kohlstechnology/eunomia-base:latest","templateSource":{"contextDir":"examples/hello-world-yaml/template3","ref":"master","uri":"https://github.com/KohlsTechnology/eunomia"},"triggers":[{"type":"Change"}]}}
gitopsconfig.eunomia.kohls.io "hello-world-yaml" deleted
I1030 14:16:27.752778   56329 round_trippers.go:423] curl -k -v -XGET  -H "User-Agent: kubectl/v1.16.2 (darwin/amd64) kubernetes/c97fe50" -H "Accept: application/json" 'https://192.168.64.9:8443/apis/eunomia.kohls.io/v1alpha1/namespaces/eunomia-hello-world-yaml-demo/gitopsconfigs?fieldSelector=metadata.name%3Dhello-world-yaml'
I1030 14:16:27.756691   56329 round_trippers.go:443] GET https://192.168.64.9:8443/apis/eunomia.kohls.io/v1alpha1/namespaces/eunomia-hello-world-yaml-demo/gitopsconfigs?fieldSelector=metadata.name%3Dhello-world-yaml 200 OK in 3 milliseconds
I1030 14:16:27.756708   56329 round_trippers.go:449] Response Headers:
I1030 14:16:27.756714   56329 round_trippers.go:452]     Cache-Control: no-cache, private
I1030 14:16:27.756717   56329 round_trippers.go:452]     Content-Type: application/json
I1030 14:16:27.756719   56329 round_trippers.go:452]     Content-Length: 2033
I1030 14:16:27.756722   56329 round_trippers.go:452]     Date: Wed, 30 Oct 2019 13:16:27 GMT
I1030 14:16:27.756744   56329 request.go:968] Response Body: {"apiVersion":"eunomia.kohls.io/v1alpha1","items":[{"apiVersion":"eunomia.kohls.io/v1alpha1","kind":"GitOpsConfig","metadata":{"annotations":{"gitopsconfig.eunomia.kohls.io/initialized":"true","kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"eunomia.kohls.io/v1alpha1\",\"kind\":\"GitOpsConfig\",\"metadata\":{\"annotations\":{},\"name\":\"hello-world-yaml\",\"namespace\":\"eunomia-hello-world-yaml-demo\"},\"spec\":{\"parameterSource\":{\"contextDir\":\"examples/hello-world-yaml/parameters\",\"ref\":\"master\"},\"resourceDeletionMode\":\"Delete\",\"resourceHandlingMode\":\"CreateOrMerge\",\"serviceAccountRef\":\"eunomia-runner-yaml\",\"templateProcessorImage\":\"quay.io/kohlstechnology/eunomia-base:latest\",\"templateSource\":{\"contextDir\":\"examples/hello-world-yaml/template3\",\"ref\":\"master\",\"uri\":\"https://github.com/KohlsTechnology/eunomia\"},\"triggers\":[{\"type\":\"Change\"}]}}\n"},"creationTimestamp":"2019-10-30T13:14:08Z","deletionGracePeriodSeconds":0,"deletionTimestamp":"2019-10-30T13:16:27Z","finalizers":["eunomia-finalizer"],"generation":5,"name":"hello-world-yaml","namespace":"eunomia-hello-world-yaml-demo","resourceVersion":"5874","selfLink":"/apis/eunomia.kohls.io/v1alpha1/namespaces/eunomia-hello-world-yaml-demo/gitopsconfigs/hello-world-yaml","uid":"8264248b-d66a-48a5-9f63-eaa00882c97c"},"spec":{"parameterSource":{"contextDir":"examples/hello-world-yaml/parameters","ref":"master","uri":"https://github.com/KohlsTechnology/eunomia"},"resourceDeletionMode":"Delete","resourceHandlingMode":"CreateOrMerge","serviceAccountRef":"eunomia-runner-yaml","templateProcessorImage":"quay.io/kohlstechnology/eunomia-base:latest","templateSource":{"contextDir":"examples/hello-world-yaml/template3","ref":"master","uri":"https://github.com/KohlsTechnology/eunomia"},"triggers":[{"type":"Change"}]}}],"kind":"GitOpsConfigList","metadata":{"continue":"","resourceVersion":"5874","selfLink":"/apis/eunomia.kohls.io/v1alpha1/namespaces/eunomia-hello-world-yaml-demo/gitopsconfigs"}}
I1030 14:16:27.757216   56329 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json" -H "User-Agent: kubectl/v1.16.2 (darwin/amd64) kubernetes/c97fe50" 'https://192.168.64.9:8443/apis/eunomia.kohls.io/v1alpha1/namespaces/eunomia-hello-world-yaml-demo/gitopsconfigs?fieldSelector=metadata.name%3Dhello-world-yaml&resourceVersion=5874&watch=true'
I1030 14:16:27.759369   56329 round_trippers.go:443] GET https://192.168.64.9:8443/apis/eunomia.kohls.io/v1alpha1/namespaces/eunomia-hello-world-yaml-demo/gitopsconfigs?fieldSelector=metadata.name%3Dhello-world-yaml&resourceVersion=5874&watch=true 200 OK in 2 milliseconds
I1030 14:16:27.759383   56329 round_trippers.go:449] Response Headers:
I1030 14:16:27.759389   56329 round_trippers.go:452]     Cache-Control: no-cache, private
I1030 14:16:27.759392   56329 round_trippers.go:452]     Content-Type: application/json
I1030 14:16:27.759395   56329 round_trippers.go:452]     Date: Wed, 30 Oct 2019 13:16:27 GMT
```

```
> k logs -n eunomia-operator                pod/eunomia-operator-69cf484c54-wffcb -f
{"level":"info","ts":1572436628.8582387,"logger":"cmd","msg":"Go Version: go1.12.6"}
{"level":"info","ts":1572436628.8582826,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1572436628.8582947,"logger":"cmd","msg":"Version of operator-sdk: v0.8.1"}
{"level":"info","ts":1572436628.8591754,"logger":"cmd","msg":"Templates initialized correctly"}
{"level":"info","ts":1572436628.8594327,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1572436628.8890915,"logger":"leader","msg":"No pre-existing lock was found."}
{"level":"info","ts":1572436628.8926587,"logger":"leader","msg":"Became the leader."}
{"level":"info","ts":1572436628.9102945,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1572436628.9105887,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"gitopsconfig-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1572436628.9106736,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"gitopsconfig-controller","source":"channel source: 0xc000592230"}
{"level":"info","ts":1572436628.9107726,"logger":"cmd","msg":"Starting the Web Server"}
{"level":"info","ts":1572436628.9107995,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1572436629.0117345,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"gitopsconfig-controller"}
{"level":"info","ts":1572436629.1128118,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"gitopsconfig-controller","worker count":1}
{"level":"info","ts":1572441248.2111485,"logger":"controller_gitopsconfig","msg":"Reconciling GitOpsConfig","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml"}
{"level":"info","ts":1572441248.211206,"logger":"controller_gitopsconfig","msg":"found instance","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1572441248.2112255,"logger":"controller_gitopsconfig","msg":"Instance needs to be initialized","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1572441248.2181456,"logger":"controller_gitopsconfig","msg":"Reconciling GitOpsConfig","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml"}
{"level":"info","ts":1572441248.2182448,"logger":"controller_gitopsconfig","msg":"found instance","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1572441248.2182968,"logger":"controller_gitopsconfig","msg":"Instance is initialized","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1572441248.2184618,"logger":"controller_gitopsconfig","msg":"Instance has a change or Webhook trigger, creating job","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1572441248.220024,"logger":"controller_gitopsconfig","msg":"Creating a new Job","job.Namespace":"eunomia-hello-world-yaml-demo","job.Name":"gitopsconfig-hello-world-yaml-bmdfu1"}
{"level":"info","ts":1572441297.6393611,"logger":"controller_gitopsconfig","msg":"Reconciling GitOpsConfig","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml"}
{"level":"info","ts":1572441297.639454,"logger":"controller_gitopsconfig","msg":"found instance","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1572441297.639478,"logger":"controller_gitopsconfig","msg":"Instance is initialized","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1572441297.6396227,"logger":"controller_gitopsconfig","msg":"Instance has a change or Webhook trigger, creating job","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1572441297.640606,"logger":"controller_gitopsconfig","msg":"Creating a new Job","job.Namespace":"eunomia-hello-world-yaml-demo","job.Name":"gitopsconfig-hello-world-yaml-whq80r"}
{"level":"info","ts":1572441321.5619705,"logger":"controller_gitopsconfig","msg":"Reconciling GitOpsConfig","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml"}
{"level":"info","ts":1572441321.5622754,"logger":"controller_gitopsconfig","msg":"found instance","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1572441321.5624123,"logger":"controller_gitopsconfig","msg":"Instance is initialized","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1572441321.562429,"logger":"controller_gitopsconfig","msg":"Instance has a change or Webhook trigger, creating job","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1572441321.5630205,"logger":"controller_gitopsconfig","msg":"Creating a new Job","job.Namespace":"eunomia-hello-world-yaml-demo","job.Name":"gitopsconfig-hello-world-yaml-9m9fog"}
{"level":"info","ts":1572441387.847938,"logger":"controller_gitopsconfig","msg":"Reconciling GitOpsConfig","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml"}
{"level":"info","ts":1572441387.84824,"logger":"controller_gitopsconfig","msg":"found instance","Request.Namespace":"eunomia-hello-world-yaml-demo","Request.Name":"hello-world-yaml","instance":"hello-world-yaml"}
{"level":"info","ts":1572441387.8492885,"logger":"controller_gitopsconfig","msg":"Instance is being deleted","instance":"hello-world-yaml"}
```

**Closed** 2019-11-04 22:58 UTC
Labels: bug
